use super::*;

#[test]
fn test_inject_hit_cluster_correctness() {
    let input = r#"
#[duration=10s]
scenario inject_hit<seed=42> {
    background {
        stream LoginWindow gen 100/s
    }
    injection {
        // 100 个实体 × 每个 5 条 = 500 条注入（背景另算：100/s × 10s = 1000 条）
        hit<src_ip: 100> for auth_fail_rule LoginWindow {
            use(action="failed") x 5
        }
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_auth_fail_plan()];

    let result = generate(&wfg, &schemas, &plans).unwrap();
    // 总条数 = 背景 1000 + 注入 500（背景与注入完全分离）
    assert_eq!(result.events.len(), 1500);

    // 100 个实体 × 每个 5 条 = 500 条注入事件
    // Count events that are inject hit events by checking src_ip pattern
    let hit_events: Vec<_> = result
        .events
        .iter()
        .filter(|e| {
            e.fields
                .get("src_ip")
                .and_then(|v| v.as_str())
                .map(|s| s.starts_with("10."))
                .unwrap_or(false)
                && e.fields
                    .get("src_ip")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .len()
                    <= 15 // typical inject IP pattern
        })
        .collect();

    // At minimum we should have all 500 injected hit events
    assert!(
        hit_events.len() >= 500,
        "expected at least 500 hit events, got {}",
        hit_events.len()
    );

    // All events should be sorted by timestamp
    for w in result.events.windows(2) {
        assert!(w[0].timestamp <= w[1].timestamp);
    }
}

#[test]
fn test_inject_filter_constraint_applied() {
    // Rule has filter: success == false
    // Generated inject events must have success = false
    let input = r#"
#[duration=5s]
scenario inject_filter<seed=42> {
    background {
        stream LoginWindow gen 100/s
    }
    injection {
        // 30 个实体 × 每个 5 条 = 150 条注入（背景另算：100/s × 5s = 500 条）
        hit<src_ip: 30> for auth_fail_rule LoginWindow {
            use(success=false) x 5
        }
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_auth_fail_plan()];

    let result = generate(&wfg, &schemas, &plans).unwrap();
    // 总条数 = 背景 500 + 注入 150
    assert_eq!(result.events.len(), 650);

    // Inject events are identified by src_ip pattern "10.x.x.x" (generated by generate_key_values)
    // Background events have different IPs from the ipv4() generator
    // Count inject events (those with src_ip starting with "10." and having typical inject pattern)
    let inject_events: Vec<_> = result
        .events
        .iter()
        .filter(|e| {
            e.fields
                .get("src_ip")
                .and_then(|v| v.as_str())
                .map(|s| s.starts_with("10.") && s.len() <= 15)
                .unwrap_or(false)
        })
        .collect();

    // Debug: print first 10 inject events
    for (i, event) in inject_events.iter().take(10).enumerate() {
        eprintln!(
            "Inject event {}: src_ip={:?}, success={:?}",
            i,
            event.fields.get("src_ip"),
            event.fields.get("success")
        );
    }

    // All inject events should have success = false due to filter
    for (i, event) in inject_events.iter().enumerate() {
        let success = event.fields.get("success").and_then(|v| v.as_bool());
        assert_eq!(
            success,
            Some(false),
            "inject event {} should have success=false due to filter, got {:?}",
            i,
            success
        );
    }

    // Run oracle — should produce alerts because inject events match filter and threshold
    let start = "2024-01-01T00:00:00Z".parse().unwrap();
    let duration = Duration::from_secs(3600);
    let oracle = run_oracle(&result.events, &plans, &start, &duration, None).unwrap();

    // We expect alerts since hit events have the correct filter value
    assert!(
        !oracle.alerts.is_empty(),
        "expected alerts from hit events with filter, got {}",
        oracle.alerts.len()
    );
}

#[test]
fn test_inject_use_predicate_conflicting_with_filter_fails() {
    let input = r#"
#[duration=5s]
scenario inject_filter_conflict<seed=42> {
    background {
        stream LoginWindow gen 100/s
    }
    injection {
        hit<src_ip: 30> for auth_fail_rule LoginWindow {
            use(success=true) x 5
        }
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_auth_fail_plan()];

    let err = match generate(&wfg, &schemas, &plans) {
        Ok(_) => panic!("generation should fail when use predicates conflict with rule filters"),
        Err(err) => err,
    };
    let rendered = err.report().render().to_string();
    assert!(
        rendered.contains("conflicts with rule step filter"),
        "unexpected error: {rendered}"
    );
}

#[test]
fn test_inject_near_miss_use_predicate_conflicting_with_filter_fails() {
    let input = r#"
#[duration=5s]
scenario inject_filter_conflict_nm<seed=42> {
    background {
        stream LoginWindow gen 100/s
    }
    injection {
        near_miss<src_ip: 30> for auth_fail_rule LoginWindow {
            use(success=true) x 5
        }
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_auth_fail_plan()];

    let err = match generate(&wfg, &schemas, &plans) {
        Ok(_) => panic!("generation should fail when use predicates conflict with rule filters"),
        Err(err) => err,
    };
    let rendered = err.report().render().to_string();
    assert!(
        rendered.contains("conflicts with rule step filter"),
        "unexpected error: {rendered}"
    );
}

#[test]
fn test_inject_use_predicates_are_step_scoped_and_typed() {
    let input = r#"
#[duration=5s]
scenario inject_step_scope<seed=42> {
    background {
        stream LoginWindow gen 40/s
    }
    injection {
        // 40 个实体 × (1 + 1) = 80 条注入（背景另算：40/s × 5s = 200 条）
        hit<src_ip: 40> for bool_chain LoginWindow {
            use(success=false) x 1
            then use(success=true) x 1
        }
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_bool_chain_plan()];

    let result = generate(&wfg, &schemas, &plans).unwrap();
    // 总条数 = 背景 200 + 注入 80
    assert_eq!(result.events.len(), 280);

    let mut by_entity: std::collections::HashMap<
        String,
        Vec<(chrono::DateTime<chrono::Utc>, bool)>,
    > = std::collections::HashMap::new();
    for event in &result.events {
        let Some(entity) = event.fields.get("username").and_then(|v| v.as_str()) else {
            continue;
        };
        if !entity.starts_with("hit_username_") {
            continue;
        }
        let Some(success) = event.fields.get("success").and_then(|v| v.as_bool()) else {
            panic!(
                "inject event should keep bool type for success, got {:?}",
                event.fields.get("success")
            );
        };
        by_entity
            .entry(entity.to_string())
            .or_default()
            .push((event.timestamp, success));
    }

    assert!(
        !by_entity.is_empty(),
        "expected inject entities with generated username prefix"
    );

    for (entity, seq) in &mut by_entity {
        seq.sort_by_key(|(ts, _)| *ts);
        assert!(
            seq.len() >= 2,
            "entity {} should have at least 2 injected events, got {}",
            entity,
            seq.len()
        );
        assert!(
            !seq[0].1,
            "entity {} first step should be success=false, got {:?}",
            entity, seq[0].1
        );
        assert!(
            seq[1].1,
            "entity {} second step should be success=true, got {:?}",
            entity, seq[1].1
        );
    }
}

#[test]
fn test_inject_near_miss_no_trigger() {
    // near_miss 的条数就是写的 `x N`：x 4 < 阈值 5，故不成簇、不触发
    let input = r#"
#[duration=10s]
scenario inject_nm<seed=42> {
    background {
        stream LoginWindow gen 100/s
    }
    injection {
        // 100 个实体 × 每个 4 条 = 400 条注入（背景另算：100/s × 10s = 1000 条）
        near_miss<src_ip: 100> for brute_force LoginWindow {
            use(action="failed") x 4
        }
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_brute_force_plan()];

    let result = generate(&wfg, &schemas, &plans).unwrap();
    // 总条数 = 背景 1000 + 注入 400
    assert_eq!(result.events.len(), 1400);

    // Run oracle — near-miss clusters should NOT produce alerts
    let start = "2024-01-01T00:00:00Z".parse().unwrap();
    let duration = Duration::from_secs(3600);
    let oracle = run_oracle(&result.events, &plans, &start, &duration, None).unwrap();
    assert_eq!(
        oracle.alerts.len(),
        0,
        "near-miss clusters should not trigger any alerts"
    );
}

#[test]
fn test_inject_hit_triggers_oracle() {
    let input = r#"
#[duration=10s]
scenario inject_oracle<seed=42> {
    background {
        stream LoginWindow gen 100/s
    }
    injection {
        // 100 个实体 × 每个 5 条 = 500 条注入 → 100 个簇
        hit<src_ip: 100> for brute_force LoginWindow {
            use(action="failed") x 5
        }
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_brute_force_plan()];

    let result = generate(&wfg, &schemas, &plans).unwrap();

    // Run oracle — hit clusters should produce alerts
    let start = "2024-01-01T00:00:00Z".parse().unwrap();
    let duration = Duration::from_secs(3600);
    let oracle = run_oracle(&result.events, &plans, &start, &duration, None).unwrap();

    // 100 个实体 × 每个 5 条 = 500 条注入 / 每簇 5 条 = 100 个簇 → 100 条告警
    assert_eq!(
        oracle.alerts.len(),
        100,
        "expected 100 alerts from 100 hit clusters, got {}",
        oracle.alerts.len()
    );

    // All alerts should have correct rule name and score
    for alert in &oracle.alerts {
        assert_eq!(alert.rule_name, "brute_force");
        assert!((alert.score - 85.0).abs() < f64::EPSILON);
        assert_eq!(alert.entity_type, "ip");
    }
}

#[test]
fn test_inject_mode_counts_are_independent_and_additive() {
    // 三种模式的数量各自写死、互不共享预算：
    //   60×5 + 25×4 + 200×1 = 600 条注入；背景另算 100/s × 10s = 1000 条
    let input = r#"
#[duration=10s]
scenario inject_budget<seed=42> {
    background {
        stream LoginWindow gen 100/s
    }
    injection {
        hit<src_ip: 60> for brute_force LoginWindow {
            use(action="failed") x 5
        }
        near_miss<src_ip: 25> for brute_force LoginWindow {
            use(action="failed") x 4
        }
        miss<src_ip: 200> for brute_force LoginWindow {
            use(action="success") x 1
        }
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_brute_force_plan()];

    let result = generate(&wfg, &schemas, &plans).unwrap();
    // 注入不再从背景配额里扣：总条数 = 背景 1000 + 注入 600
    assert_eq!(result.events.len(), 1600);

    let injected = result
        .events
        .iter()
        .filter(|e| {
            e.fields
                .get("src_ip")
                .and_then(|v| v.as_str())
                .is_some_and(|s| s.starts_with("10.") && s.len() <= 15)
        })
        .count();
    assert!(
        injected >= 600,
        "三种模式的注入量必须各自写死并相加（60×5 + 25×4 + 200×1 = 600），实际 {injected}"
    );
}

/// 注入量超过背景配额时背景也不被挤掉：总条数 = 背景 + 注入。
///
/// 旧口径是 `背景 = 配额 − 注入`（`saturating_sub`），注入超配额时背景被清零，
/// 总条数只剩注入——那是"配额预算"模型的残留（设计 §3.4 要求完全分离）。
#[test]
fn background_is_not_squeezed_when_inject_exceeds_it() {
    // 背景 10/s × 1s = 10 条；注入 8 实体 × 5 条 = 40 条 → 总 50（旧口径 40）
    let input = r#"
#[duration=1s]
scenario inject_over_background<seed=42> {
    background {
        stream LoginWindow gen 10/s
    }
    injection {
        hit<src_ip: 8> for brute_force LoginWindow {
            use(action="failed") x 5
        }
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_brute_force_plan()];

    let result = generate(&wfg, &schemas, &plans).unwrap();
    assert_eq!(result.events.len(), 10 + 40);

    // 注入侧实际发了 8 实体 × 5 条，且背景 10 条一条不少。
    let injected_values: std::collections::HashSet<&str> = result
        .inject_entities
        .iter()
        .filter_map(|entity| entity.value.as_str())
        .collect();
    assert_eq!(injected_values.len(), 8);

    let injected = result
        .events
        .iter()
        .filter(|event| {
            event
                .fields
                .get("src_ip")
                .and_then(|v| v.as_str())
                .is_some_and(|sip| injected_values.contains(sip))
        })
        .count();
    assert_eq!(injected, 40);
    assert_eq!(result.events.len() - injected, 10, "背景不被注入挤压");
}

#[test]
fn test_inject_deterministic() {
    let input = r#"
#[duration=5s]
scenario inject_det<seed=42> {
    background {
        stream LoginWindow gen 100/s
    }
    injection {
        hit<src_ip: 30> for brute_force LoginWindow {
            use(action="failed") x 5
        }
    }
}
"#;
    let wfg = parse_wfg(input).unwrap();
    let schemas = vec![make_login_schema()];
    let plans = vec![make_brute_force_plan()];

    let result1 = generate(&wfg, &schemas, &plans).unwrap();
    let result2 = generate(&wfg, &schemas, &plans).unwrap();

    assert_eq!(result1.events.len(), result2.events.len());
    for (e1, e2) in result1.events.iter().zip(result2.events.iter()) {
        assert_eq!(e1.timestamp, e2.timestamp);
        assert_eq!(e1.fields, e2.fields);
    }
}
