[[connectors]]
id = "file_arrow"
type = "file"
allow_override = ["base", "file", "fields", "sync"]

[connectors.params]
protocol = "arrow"
base = "../data/out_dat/alerts"
file = "default.arrow"
fields = ["sip", "alert_type"]
sync = false
