[[connectors]]
id = "arrow_ipc_sink"
type = "arrow-ipc"
allow_override = ["target", "tag", "fields"]

[connectors.params]
target = "tcp://127.0.0.1:9801"
tag = "nginx_events"
fields = [
    { name = "sip", type = "ip" },
    { name = "recv_time", type = "time" },
    { name = "request", type = "chars" },
    { name = "status", type = "digit" },
    { name = "digit", type = "digit" },
    { name = "chars", type = "chars" },
]
