version = "1.0"
[sink_group]
name = "weak_pwd_out"
windows = ["weak_pwd_alerts"]
[[sink_group.sinks]]
connect = "file_json_sink"
name = "weak_pwd_json"
[sink_group.sinks.params]
base = "../data/out_dat/alerts"
file = "weak_pwd.ndjson"
